# Generated by Django 5.1.2 on 2024-10-24 12:38

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, null=False, blank=False
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=50,
                        validators=[users.validators.validate_password],
                        null=False,
                        blank=False,
                    ),
                ),
                ("access_rights", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=False, blank=False)),
                ("birth_date", models.DateField(null=False, blank=False)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        null=False,
                        blank=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен начинаться с +7 или 8 и содержать всего 11 цифр.",
                                regex="^(?:\\+7|8)\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("city", models.CharField(max_length=255, null=False, blank=False)),
                (
                    "total_spent",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=20
                    ),
                ),
                (
                    "purchase_to_return_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5
                    ),
                ),
            ],
        ),
    ]
